# generated by datamodel-codegen:
#   filename:  openapi_plataforma.json
#   timestamp: 2026-08-05T15:09:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class AirflowConfigRequest(BaseModel):
    retries: int | None = Field(None, title='Retries')
    retry_delay_minutes: int | None = Field(None, title='Retry Delay Minutes')
    execution_timeout_minutes: int | None = Field(
        None, title='Execution Timeout Minutes'
    )
    sla_minutes: int | None = Field(None, title='Sla Minutes')
    tags: list[str] | None = Field(None, title='Tags')
    pool: str | None = Field(None, title='Pool')


class AssetState(Enum):
    draft = 'draft'
    active = 'active'
    deprecated = 'deprecated'
    archived = 'archived'


class ComputeConfigRequest(BaseModel):
    engine: str | None = Field(None, title='Engine')
    staging_bucket: str | None = Field(None, title='Staging Bucket')
    num_workers: int | None = Field(None, title='Num Workers')
    machine_type: str | None = Field(None, title='Machine Type')


class DatabaseEndpointCreateRequest(BaseModel):
    name: str = Field(..., title='Name')
    credential_ref: str = Field(..., title='Credential Ref')
    technical_description: str | None = Field('', title='Technical Description')


class DiscoveryRunResponse(BaseModel):
    id: str = Field(..., title='Id')
    asset_id: str = Field(..., title='Asset Id')
    triggered_by: str = Field(..., title='Triggered By')
    status: str = Field(..., title='Status')
    started_at: AwareDatetime | None = Field(..., title='Started At')
    completed_at: AwareDatetime | None = Field(..., title='Completed At')
    objects_discovered: int = Field(..., title='Objects Discovered')
    fields_discovered: int = Field(..., title='Fields Discovered')
    error_message: str | None = Field(..., title='Error Message')


class DriftApprovalResponse(BaseModel):
    id: str = Field(..., title='Id')
    discovery_run_id: str = Field(..., title='Discovery Run Id')
    asset_id: str = Field(..., title='Asset Id')
    object_id: str = Field(..., title='Object Id')
    field_name: str | None = Field(..., title='Field Name')
    change_type: str = Field(..., title='Change Type')
    severity_description: str = Field(..., title='Severity Description')
    decision: str = Field(..., title='Decision')
    decided_by: str | None = Field(..., title='Decided By')
    decided_at: AwareDatetime | None = Field(..., title='Decided At')
    owner_notes: str | None = Field(..., title='Owner Notes')


class DriftDecisionRequest(BaseModel):
    decision: str = Field(..., description="'approved' or 'rejected'", title='Decision')
    decided_by: str = Field(..., title='Decided By')
    notes: str | None = Field(None, title='Notes')


class EndpointType(Enum):
    database = 'database'
    rest_api = 'rest_api'
    sftp = 'sftp'
    cloud_bucket = 'cloud_bucket'
    etl_flow = 'etl_flow'
    nosql = 'nosql'


class ExtractionObjectRequest(BaseModel):
    object_id: str = Field(..., title='Object Id')
    load_strategy: str | None = Field(None, title='Load Strategy')
    watermark_column: str | None = Field(None, title='Watermark Column')
    page_size: int | None = Field(None, title='Page Size')
    partition_column: str | None = Field(None, title='Partition Column')
    compression: str | None = Field(None, title='Compression')
    encoding: str | None = Field(None, title='Encoding')
    extraction_query: str | None = Field(None, title='Extraction Query')
    credential_ref: str | None = Field(None, title='Credential Ref')


class HarnessSchemaResponse(BaseModel):
    type: str = Field(
        ..., description="The root type of the schema (usually 'object').", title='Type'
    )
    properties: dict[str, Any] = Field(
        ..., description='The properties defined in the schema.', title='Properties'
    )


class HealthResponse(BaseModel):
    status: str = Field(..., title='Status')
    version: str = Field(..., title='Version')


class LineageNodeSchema(BaseModel):
    object_id: str = Field(..., title='Object Id')
    column_name: str = Field(..., title='Column Name')
    transformation: str | None = Field(None, title='Transformation')


class NoSqlEndpointCreateRequest(BaseModel):
    name: str = Field(..., title='Name')
    credential_ref: str = Field(..., title='Credential Ref')
    technical_description: str | None = Field('', title='Technical Description')


class PipelineResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    pipeline_type: str = Field(..., title='Pipeline Type')
    owner_email: str = Field(..., title='Owner Email')
    source_asset: str | None = Field('', title='Source Asset')
    destination_asset: str | None = Field(None, title='Destination Asset')
    cron_schedule: str | None = Field(None, title='Cron Schedule')


class PipelineRunResponse(BaseModel):
    id: str = Field(..., title='Id')
    pipeline_id: str = Field(..., title='Pipeline Id')
    pipeline_name: str = Field(..., title='Pipeline Name')
    dag_run_id: str = Field(..., title='Dag Run Id')
    status: str = Field(..., title='Status')


class PipelineYamlExportResponse(BaseModel):
    pipeline_id: str = Field(
        ...,
        description='Unique identifier of the pipeline (matches dag_id).',
        title='Pipeline Id',
    )
    pipeline_yaml: str = Field(
        ...,
        description='Canonical YAML representation of the pipeline.',
        title='Pipeline Yaml',
    )


class PolicyTag(Enum):
    PII = 'PII'
    RESTRICTED = 'RESTRICTED'
    PUBLIC = 'PUBLIC'
    CONFIDENTIAL = 'CONFIDENTIAL'


class QualityGateReportRequest(BaseModel):
    metrics: dict[str, Any] = Field(..., title='Metrics')


class QualityGateReportResponse(BaseModel):
    run_id: str = Field(..., title='Run Id')
    status: str = Field(..., title='Status')
    violations: list[str] = Field(..., title='Violations')


class QualityRuleRequest(BaseModel):
    type: str = Field(..., title='Type')
    column: str | None = Field(None, title='Column')
    value: float | None = Field(None, title='Value')


class ReadyResponse(BaseModel):
    status: str = Field(..., title='Status')
    components: dict[str, str] = Field(..., title='Components')


class RestApiEndpointCreateRequest(BaseModel):
    name: str = Field(..., title='Name')
    credential_ref: str = Field(..., title='Credential Ref')
    base_url: str | None = Field('', title='Base Url')
    auth_type: str | None = Field('', title='Auth Type')
    technical_description: str | None = Field('', title='Technical Description')


class TriggerDiscoveryRequest(BaseModel):
    triggered_by: str = Field(
        ...,
        description="Who or what triggered this run (e.g. 'manual', 'scheduler')",
        title='Triggered By',
    )


class TriggerRunRequest(BaseModel):
    triggered_by: str = Field(..., title='Triggered By')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class ValidationErrorDetail(BaseModel):
    json_pointer: str = Field(
        ...,
        description='JSON Pointer (RFC 6901) indicating the exact field with the error.',
        title='Json Pointer',
    )
    error_code: str = Field(
        ...,
        description='Categorized error code (e.g., MISSING_ID, INVALID_SQL).',
        title='Error Code',
    )
    message: str = Field(
        ..., description='Technical message describing the problem.', title='Message'
    )
    suggestion: str = Field(
        ...,
        description='Direct and actionable corrective suggestion.',
        title='Suggestion',
    )


class PipelineType(Enum):
    relational = 'relational'
    file = 'file'
    api = 'api'


class ValidationRequest(BaseModel):
    pipeline_yaml: str = Field(
        ...,
        description='Raw YAML content of the pipeline configuration.',
        title='Pipeline Yaml',
    )
    pipeline_type: PipelineType | None = Field(
        'relational',
        description='Type of pipeline to apply specific validation rules.',
        title='Pipeline Type',
    )


class ValidationResponse(BaseModel):
    is_valid: bool = Field(
        ...,
        description='True if the YAML meets all platform requirements.',
        title='Is Valid',
    )
    errors: list[ValidationErrorDetail] | None = Field(
        None,
        description='List of validation errors; empty if is_valid is True.',
        title='Errors',
    )


class AssetCreateRequest(BaseModel):
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    owner_email: str = Field(..., title='Owner Email')
    tags: list[str] | None = Field([], title='Tags')
    policy_tags: list[PolicyTag] | None = Field([], title='Policy Tags')
    discovery_schedule: str = Field(..., title='Discovery Schedule')
    discovery_scope_include: list[str] | None = Field(
        [], title='Discovery Scope Include'
    )
    discovery_scope_exclude: list[str] | None = Field(
        [], title='Discovery Scope Exclude'
    )


class AssetResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    owner_email: str = Field(..., title='Owner Email')
    tags: list[str] = Field(..., title='Tags')
    policy_tags: list[PolicyTag] = Field(..., title='Policy Tags')
    state: AssetState
    discovery_schedule: str = Field(..., title='Discovery Schedule')
    discovery_scope_include: list[str] = Field(..., title='Discovery Scope Include')
    discovery_scope_exclude: list[str] = Field(..., title='Discovery Scope Exclude')
    endpoint_id: str | None = Field(..., title='Endpoint Id')


class AssetUpdateRequest(BaseModel):
    description: str | None = Field(None, title='Description')
    tags: list[str] | None = Field(None, title='Tags')
    policy_tags: list[PolicyTag] | None = Field(None, title='Policy Tags')
    endpoint_name: str | None = Field(None, title='Endpoint Name')


class CreatePipelineRequest(BaseModel):
    name: str = Field(..., title='Name')
    pipeline_type: str = Field(..., title='Pipeline Type')
    owner_email: str = Field(..., title='Owner Email')
    source_asset: str | None = Field(None, title='Source Asset')
    cron_schedule: str = Field(..., title='Cron Schedule')
    destination_asset: str | None = Field(None, title='Destination Asset')
    destination_objects: list[dict[str, Any]] | None = Field(
        None, title='Destination Objects'
    )
    source_objects: list[ExtractionObjectRequest] | None = Field(
        None, title='Source Objects'
    )
    compute: ComputeConfigRequest | None = None
    quality_rules: list[QualityRuleRequest] | None = Field(None, title='Quality Rules')
    airflow_config: AirflowConfigRequest | None = None
    source_asset_id: str | None = Field(None, title='Source Asset Id')
    destination_asset_id: str | None = Field(None, title='Destination Asset Id')


class EndpointResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    type: EndpointType


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class LineageGraphResponse(BaseModel):
    upstream: list[LineageNodeSchema] | None = Field(None, title='Upstream')
    downstream: list[LineageNodeSchema] | None = Field(None, title='Downstream')
